# Generated by Django 2.2.6 on 2019-10-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='WaitEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_time_str', models.CharField(max_length=60)),
                ('wait_time_mins', models.IntegerField()),
                ('num_waiting', models.IntegerField()),
                ('creation_date_utc', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctdmv.Branch')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctdmv.Service')),
            ],
            options={
                'ordering': ('creation_date_utc', 'branch', 'service'),
                'unique_together': {('creation_date_utc', 'branch', 'service')},
            },
        ),
    ]
