# Generated by Django 2.2.6 on 2019-10-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctdmv', '0002_auto_20191018_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitentry',
            options={'ordering': ('-creation_date_utc', 'branch', 'service')},
        ),
    ]
